### ISSUE TITLE
Enable Connections graph

### ISSUE THREAD

**Issue by jakubukrop** [vacuumlabs/verejne.digital#103]
Connections will show Graph based on `showGraph` property. It can be currently set only directly via URL query. Example:
http://localhost:3000/prepojenia?eid1=Miro%20Noga&eid2=%C5%A0tefan%20Skr%C3%BAcan%C3%BD&graph=true

Task is to do this from UI (toggle button, checkbox etc.)

**Comment by mpinter** [comment]
Done
