### ISSUE TITLE
Handle empty search results

### ISSUE THREAD

**Issue by jakubukrop** [vacuumlabs/verejne.digital#106]
Prevent useless failing calls such as `getInfos?eids=`.
Also, add user friendly message that nothing was found.
Fixes needed in:
- Public
- Connections

**Comment by PeterPsota** [comment]
Public part of problem is fixed in [PR #177](https://github.com/verejnedigital/verejne.digital/pull/177).
Looking info connections

**Comment by PeterPsota** [comment]
User friendly message added in [PR #180](https://github.com/verejnedigital/verejne.digital/pull/180) using Statuses component.
I have not managed  to find any failing calls, @jakubukrop could you please provide steps to reproduce the problem or confirm it is fixed already?
