### ISSUE TITLE
Make "Profil" search input look nicer

### ISSUE THREAD

**Issue by TomasJendek** [vacuumlabs/verejne.digital#135]
Search input in "Profile" 
- align to the center
- make it more narrow 
- add "submit" button (may be the same as in search input in verejne data)

<img width="1223" alt="screen shot 2018-09-19 at 13 09 24" src="https://user-images.githubusercontent.com/1598770/45806039-52946600-bcc0-11e8-802a-cc7063c73a1b.png">

**Comment by PeterPsota** [comment]
https://github.com/verejnedigital/verejne.digital/pull/209
