### ISSUE TITLE
Mismatch of relation and info

### ISSUE THREAD

**Issue by PeterPsota** [vacuumlabs/verejne.digital#140]
http://localhost:3000/profil/809 -> 'vztahy' -> 'ZUTE spol sro' -> loads 'VMF sro'
module/verejne loads 'ZUTE' correctly

![image](https://user-images.githubusercontent.com/18385255/45871321-84bfc980-bd8d-11e8-829f-8ee0d1eebb45.png)
![image](https://user-images.githubusercontent.com/18385255/45871368-a325c500-bd8d-11e8-9a44-887c63f65ceb.png)

**Comment by mirecmrozek** [comment]
This is a backend issue. It should be fixed once they refresh whole database.
