### ISSUE TITLE
Make Notable connections inaccessible

### ISSUE THREAD

**Issue by mirecmrozek** [vacuumlabs/verejne.digital#154]
For upcoming launch, only searching connection between two entities should be allowed, until notable connections is ready.
Just check if also second input is empty.
Also, change the sidebar text appropriately.

**Comment by matejbalog** [comment]
Is it starting to look more likely that #147 or #152 won't be able to make it for the upcoming launch? It would be great if notable connections were still accessible at least until the launch time, as they are useful for debugging. :) Perhaps the code disabling them could be commented out for the meantime, or controlled by a flag. (The sidebar text can be changed whenever convenient.) Thanks!
