### ISSUE TITLE
Fix show on map button ignoring nearby markers

### ISSUE THREAD

**Issue by PeterPsota** [vacuumlabs/verejne.digital#176]
The show on map button sometimes does not show surrounding markers.
Happens to me when the marker was selected before
Click on marker, choose entity from addresses displayed, move map away from marker, click 'show on map' button of chosen entity.
![image](https://user-images.githubusercontent.com/18385255/46539225-34c92280-c8b6-11e8-99f5-d5ad661a4fd9.png)
![image](https://user-images.githubusercontent.com/18385255/46539278-56c2a500-c8b6-11e8-94cd-0dc1ceb54353.png)

**Comment by Zygro** [comment]
Don't think I will be able to fix this. Could be an issue with `data-provider` library, because `addressesProvider` gets called with correct url, but no request for addresses is sent.
