### ISSUE TITLE
Create stripped down version of Vyhladavanie site

### ISSUE THREAD

**Issue by mirecmrozek** [vacuumlabs/verejne.digital#215]
1. add autocomplete to top
2. under it add Map from Profile detail, doesn't need to actually have anything on it, for now, it's enough to check how it affects layout (also move it to `shared/` folder)
3. under map add a notable graph
4. under graph add 2 columns of `Info` components
It should look like this: https://photos.app.goo.gl/jwJeKkdfirTUDMFu7

**Comment by mpinter** [comment]
Done on the hackathon
