### ISSUE TITLE
Rename ./ComponentName/index.js into ComponentName/ComponentName.js

### ISSUE THREAD

**Issue by mpinter** [vacuumlabs/verejne.digital#69]
.. becase the tooling breaks otherwise (if you use vs code / atom / webstorm, which most of us do):

- when you try searching ctlr+P for filename it works poorly when every file is called index.js
- when you have enough files open, you see just 'index.js' in the top tabs, and at glance don't know which ones
- when you search across multiple files, you'll find matches in multiple 'index.js' files, and at glance don't know which ones

You can use the index exports when you have a bunch of components you tend to import all at once somewhere and don't want multiple lines of imports - the index.js should then contain just 're-exports' of these and logic should still be placed in components themselves (AFAIK this is not used anywhere in the project at the moment, so no worries).

**Comment by mpinter** [comment]
@Riko196 can I close this ? I remember it being done.

**Comment by Riko196** [comment]
Yes, you can
