### ISSUE TITLE
Map addresses are sometimes too close

### ISSUE THREAD

**Issue by jakubukrop** [vacuumlabs/verejne.digital#76]
https://beta.verejne.digital/verejne?lat=48.148733&lng=17.106567&zoom=22
There are 2 addresses there:
https://verejne.digital/api/v/getAddresses?level=0&lat1=48.14870736601824&lng1=17.106264031392357&lat2=48.14879863394114&lng2=17.106885968607685

```
[{
    "lat": 48.148731,
    "tradewithgovernment": false,
    "address_id": 10998,
    "lng": 17.1065547
}, {
    "lat": 48.148731,
    "tradewithgovernment": false,
    "address_id": 197793,
    "lng": 17.1065548
}]
```
They are drawn too close no know which one am I clicking.

**Comment by mpinter** [comment]
Should we do anything about this ? How about just letting the user zoom in more ?

**Comment by jakubukrop** [comment]
There are 2 possibilities
- harder: detect these cases and either reposition or merge such addresses
- easier: let the user zoom in more (but clicking on address zooms out, so you need to figure that out too), also you may need to zoom very very much to differentiate those two addresses

**Comment by ifeelfishy** [comment]
http://localhost:3000/verejne?lat=48.148528&lng=17.107725&zoom=22

tam je ich az 5 napriklad, 
podla mna je vhodne ich klastrovat aj na maximalnom zoome a ked uz sa neda priblizit a kliknes na kluster tak ti nacita detaily zo vsetkych entit v tom klastri

**Comment by mpinter** [comment]
Done
